# Generated by Django 5.1.4 on 2024-12-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Rate',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='ServiceName',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='CustomerName',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='TransactionCost',
            new_name='transaction_cost',
        ),
    ]
